### ISSUE TITLE
character base support

### ISSUE THREAD

**Issue by nodren** [feendrache/Godot4_msca#1]
I see this isn't added per your documentation, but you mention there's a JSON file there, I'd be happy to contribute the fix to your project if you could give me some pointers on what needs to be changed to support character base

**Comment by feendrache** [comment]
Oh sorry, didn't see the ticket, missed the mail
You could fix it for yourself, but i won't maintain the plugin for the character base, sorry. 
The JSON and the base class for the reading of the json are in the project.
